// <auto-generated />
using GW2CraftCalculator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GW2CraftCalculator.Data.Migrations
{
    [DbContext(typeof(Gw2DataContext))]
    [Migration("20240614141018_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.5");

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.Item", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemGroup")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Specifications")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeInputId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RecipeOutputId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RecipeInputId");

                    b.HasIndex("RecipeOutputId");

                    b.ToTable("MysticForgeRecipes");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("InputAmountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InputAmountId");

                    b.HasIndex("ItemId");

                    b.ToTable("MysticForgeRecipeInputs");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeInputAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MysticForgeRecipeInputAmount");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputAmountId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("OutputAmountId");

                    b.ToTable("MysticForgeRecipeOutputs");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeOutputAmount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("MysticForgeRecipeOutputAmount");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.SalvageRecipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalvageInputId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalvageOutputId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SalvageInputId");

                    b.HasIndex("SalvageOutputId");

                    b.ToTable("SalvageRecipes");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.SalvageRecipeInput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SalvageKitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("SalvageKitId");

                    b.ToTable("SalvageRecipeInput");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.SalvageRecipeOutput", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OutputAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("SalvageRecipeOutput");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.VendorCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrencyType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VendorItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VendorItemId");

                    b.ToTable("VendorCost");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.VendorItem", b =>
                {
                    b.HasBaseType("GW2CraftingCalculator.Models.Data.Item");

                    b.Property<int>("ItemAmount")
                        .HasColumnType("INTEGER");

                    b.ToTable("VendorItem");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.VendorItemSalvageKit", b =>
                {
                    b.HasBaseType("GW2CraftingCalculator.Models.Data.VendorItem");

                    b.Property<decimal>("ChanceOfRareMaterials")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ChanceOfSalvagingUpgrades")
                        .HasColumnType("TEXT");

                    b.Property<int>("SalvageUpgradesType")
                        .HasColumnType("INTEGER");

                    b.ToTable("VendorItemSalvageKit");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipe", b =>
                {
                    b.HasOne("GW2CraftingCalculator.Models.Data.MysticForgeRecipeInput", "RecipeInput")
                        .WithMany("MysticForgeRecipes")
                        .HasForeignKey("RecipeInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GW2CraftingCalculator.Models.Data.MysticForgeRecipeOutput", "RecipeOutput")
                        .WithMany("MysticForgeRecipes")
                        .HasForeignKey("RecipeOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RecipeInput");

                    b.Navigation("RecipeOutput");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeInput", b =>
                {
                    b.HasOne("GW2CraftingCalculator.Models.Data.MysticForgeRecipeInputAmount", "InputAmount")
                        .WithMany("RecipeInputs")
                        .HasForeignKey("InputAmountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GW2CraftingCalculator.Models.Data.Item", "Item")
                        .WithMany("RecipeInputItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InputAmount");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeOutput", b =>
                {
                    b.HasOne("GW2CraftingCalculator.Models.Data.Item", "Item")
                        .WithMany("RecipeOutputItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GW2CraftingCalculator.Models.Data.MysticForgeRecipeOutputAmount", "OutputAmount")
                        .WithMany("RecipeOutputs")
                        .HasForeignKey("OutputAmountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("OutputAmount");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.SalvageRecipe", b =>
                {
                    b.HasOne("GW2CraftingCalculator.Models.Data.SalvageRecipeInput", "SalvageInput")
                        .WithMany("SalvageRecipes")
                        .HasForeignKey("SalvageInputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GW2CraftingCalculator.Models.Data.SalvageRecipeOutput", "SalvageOutput")
                        .WithMany("SalvageRecipes")
                        .HasForeignKey("SalvageOutputId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalvageInput");

                    b.Navigation("SalvageOutput");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.SalvageRecipeInput", b =>
                {
                    b.HasOne("GW2CraftingCalculator.Models.Data.Item", "Item")
                        .WithMany("SalvageInputs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GW2CraftingCalculator.Models.Data.VendorItemSalvageKit", "SalvageKit")
                        .WithMany()
                        .HasForeignKey("SalvageKitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("SalvageKit");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.SalvageRecipeOutput", b =>
                {
                    b.HasOne("GW2CraftingCalculator.Models.Data.Item", "Item")
                        .WithMany("SalvageOutputs")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.VendorCost", b =>
                {
                    b.HasOne("GW2CraftingCalculator.Models.Data.VendorItem", "VendorItem")
                        .WithMany("Cost")
                        .HasForeignKey("VendorItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VendorItem");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.VendorItem", b =>
                {
                    b.HasOne("GW2CraftingCalculator.Models.Data.Item", null)
                        .WithOne()
                        .HasForeignKey("GW2CraftingCalculator.Models.Data.VendorItem", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.VendorItemSalvageKit", b =>
                {
                    b.HasOne("GW2CraftingCalculator.Models.Data.VendorItem", null)
                        .WithOne()
                        .HasForeignKey("GW2CraftingCalculator.Models.Data.VendorItemSalvageKit", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.Item", b =>
                {
                    b.Navigation("RecipeInputItems");

                    b.Navigation("RecipeOutputItems");

                    b.Navigation("SalvageInputs");

                    b.Navigation("SalvageOutputs");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeInput", b =>
                {
                    b.Navigation("MysticForgeRecipes");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeInputAmount", b =>
                {
                    b.Navigation("RecipeInputs");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeOutput", b =>
                {
                    b.Navigation("MysticForgeRecipes");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.MysticForgeRecipeOutputAmount", b =>
                {
                    b.Navigation("RecipeOutputs");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.SalvageRecipeInput", b =>
                {
                    b.Navigation("SalvageRecipes");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.SalvageRecipeOutput", b =>
                {
                    b.Navigation("SalvageRecipes");
                });

            modelBuilder.Entity("GW2CraftingCalculator.Models.Data.VendorItem", b =>
                {
                    b.Navigation("Cost");
                });
#pragma warning restore 612, 618
        }
    }
}
